### PR TITLE
Remove Manifests from reference tests

### PR DESCRIPTION
**Pull request by gdalle**
Following the discussion in #415, the reference test suite needs weakening.
As soon as PkgTemplates.jl installs dependencies that fall outside the standard library, it is impossible (or very cumbersome) to control that a specific version of _every subdependency_ is selected. As a result, I only include `Project.toml` files in the reference tests, and no longer `Manifest.toml` files. In fact, the latter are dropped from the repo altogether thanks to `.gitignore`.

Ping @hannahilea, this is an easy review

### CODE REVIEW

**Comment by nickrobinson251** [comment]
do you know why we were ever including these?

**Comment by gdalle** [comment]
> do you know why we were ever including these?

I wasn't there when the ancient code was written, but I can't think of a compelling reason

**Comment by nickrobinson251** [comment]
could you please take a quick look in the history to check there wasn't a good reason

otherwise, i've no objection to this

**Comment by gdalle** [comment]
For one thing there is https://github.com/JuliaCI/PkgTemplates.jl/pull/143: it's useful to check that the parent package is indeed `dev`-ed in the docs environment, and this cannot be seen from the Project alone

**Comment by nickrobinson251** [comment]
nice find! i think that's maybe an important test -- can we keep that test somehow? e.g. keep the `docs/Manifest.toml` (perhaps with a more limited test that just checks for the presence of the package we expect to be dev'ed)?

**Review by nickrobinson251 — APPROVED** [review]
thanks!

**Comment by hannahilea** [comment]
Nice!

Might be worth filing issue so that adding back coverage of https://github.com/JuliaCI/PkgTemplates.jl/pull/422#issuecomment-1701060143 isn't lost

**Comment by nickrobinson251** [comment]
don't we still have that coverage, because we kept the `docs/Manifest.toml`? Or are we filtering them out too? As far as i understand, we should be able to guarantee the docs/Manifest.toml versions (for a fixed Documenter version), no?

**Comment by hannahilea** [comment]
You're right---we're only filtering out `joinpath("test", "Manifest.toml"))`, not  all "Manifest.toml". Good!

**Comment by gdalle** [comment]
I think it is related to https://github.com/JuliaCI/PkgTemplates.jl/issues/423

**Pull request merged**
