### PR TITLE
Fix a typo in docs of `render_file`

### PR DESCRIPTION
**Pull request by singularitti**

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Thanks!

I'm not sure why CI is failing here. @nickrobinson251 @christopher-dG Any idea?

**Comment by DilumAluthge** [comment]
(@nickrobinson251 @christopher-dG I'm not sure who the active maintainer of this package is. So if it's not you, would you mind letting me know who is, so that I can ping the right person. Sorry in advance if I've pinged the wrong person.)

**Comment by hyrodium** [comment]
Ah, I found these related issues: https://github.com/JuliaCI/PkgTemplates.jl/issues/370, https://github.com/JuliaLang/Pkg.jl/issues/3185

**Comment by oxinabox** [comment]
We should merge this

**Review by nickrobinson251 — COMMENTED** [review]
thanks!

**Pull request merged**
