### PR TITLE
Switch default julia compat to 1.6.7

### PR DESCRIPTION
**Pull request by gdalle**
Most interesting changes:

- `src/template.jl`
- `src/plugins/ci.jl`
- `test/interactive`
- `test/show`

I still need advice on how to modify the interactive tests. For now we can only pick a 1.x.0, and it would be nice to have a default 1.6.7, right?

### CODE REVIEW

**Comment by gdalle** [comment]
This one is good to go. I haven't checked why the order of Julia versions changes in CI files, but if it's a problem I can fix it

**Comment by oxinabox** [comment]
I'm fine with this. Though rumour has it that 1.10 is being considered for new LTS.
But we will need to keep testing something <=1.7 for interactive tests anyway.

**Review by oxinabox — APPROVED** [review]
I am fine with this, though rumour has it 1.10 is being considered for new LTS

**Comment by gdalle** [comment]
> I am fine with this, though rumour has it 1.10 is being considered for new LTS

It probably won't be 1.10.0 though. And we have no timeline on this (probably close to 1.11 release). So this change still makes sense in the meantime

**Pull request merged**
