### PR TITLE
support JULIA_REFERENCETESTS_UPDATE env var in tests

### PR DESCRIPTION
**Pull request by simeonschaub**
to disable the interactive prompt as it was somehow broken for me locally. Also bumps the Julia version for reference tests to 1.10.6

### CODE REVIEW

**Comment by oxinabox** [comment]
I wonder if we should use the enviroment variable
`JULIA_REFERENCETESTS_UPDATE`
Which is what is used by ReferenceTests.jl (Ideally we would just be using ReferenceTests.jl)

**Review by oxinabox — APPROVED** [review]

**Review by oxinabox — APPROVED** [review]

**Comment by oxinabox** [comment]
I have invited you to be a collaborator on the package.
Once you accept feel free to merge when happy.
Usual ColPrac stuff applies: don't merge your own PR without someone (even if they don't have commit rights) approving it.

**Comment by simeonschaub** [comment]
Cool, thanks!

**Comment by simeonschaub** [comment]
Ah, I don't think I can change repo settings as a collaborator so someone else will have to change the required job to 1.10.6 first

**Pull request merged**
