### PR TITLE
Update TagBot template

### LINKED ISSUE #403: TagBot template is out of date
The TagBot template was updated about 6 months ago, adding many more explicit permissions.

See the [example file](https://github.com/JuliaRegistries/TagBot/blob/master/example.yml) and the [README](https://github.com/JuliaRegistries/TagBot/blob/master/README.md).

I could not get TagBot to work with my newly released package [PkgToSoftwareBOM.jl](https://github.com/SamuraiAku/PkgToSoftwareBOM.jl) until I had updated my TagBot file to match what the developers recommended.

See the [TagBot issue](https://github.com/SamuraiAku/PkgToSoftwareBOM.jl/issues/12) in my repository.

### PR DESCRIPTION
**Pull request by SamuraiAku**
Resolves #403

### CODE REVIEW

**Comment by oxinabox** [comment]
Awesome.
Note the julia 1.7.2 tests are failing.
That is likely because we only do testing of reference file and interative mode in julia 1.7.2

So we need julia 1.7.2 to pass before we can merge this

**Comment by SamuraiAku** [comment]
@oxinabox Did you want me to update the tests? Can you give me some pointers as to what files need to be changed?  I am not familiar with your test setup.

**Comment by SamuraiAku** [comment]
I managed to figure out what files to update. All CI tests are passing now.

**Comment by oxinabox** [comment]
thanks

**Pull request merged**
