### PR TITLE
Start from v1.0.0-DEV

### LINKED ISSUE #387: Default to Project.toml v1.0.0
Currently the default version number if you don't specify is 0.1.0 
I believe it should be 1.0.0-DEV.
Since the version number should be 1.0.0 when it is first released (i.e. registered).
So there is no point having it on anything else since before then it doesn't matter

I thought we made this change back when Invenia stopped doing 0.x versions.
But it seems not.

Is this a breaking change?

I talked about this in some detail on twitter recently
https://twitter.com/oxinabox_frames/status/1620538988842065920

### PR DESCRIPTION
**Pull request by oxinabox**
Will close #387 

Some tests need amending, I am going to let CI tell me which

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Review by nickrobinson251 — APPROVED** [review]
what happens if someone tries to register a package with version `"1.0.0-DEV"`? does the registry just tell them to remove the `-DEV`?

I'm in favour of starting from `v1.0.0`, just wondering how to keep as beginner-friendly as possible

**Comment by DilumAluthge** [comment]
> what happens if someone tries to register a package with version `"1.0.0-DEV"`? does the registry just tell them to remove the `-DEV`?

Yeah, Registrator will reply with a comment that says "pre-release versions are not allowed".

**Comment by oxinabox** [comment]
I don't have merge rights on this repo.
Can someone merge this and tag a release?

**Comment by nickrobinson251** [comment]
i also no longer have merge rights 😞

**Comment by nickrobinson251** [comment]
@DilumAluthge can you maybe give me and @oxinabox rights on this repo?

**Comment by DilumAluthge** [comment]
Yeah one sex

**Comment by DilumAluthge** [comment]
Alright invited both of tou

**Comment by DilumAluthge** [comment]
You should receive an invitation in your email. I think you'll need to "accept" the invitation in order to receive access.

**Comment by nickrobinson251** [comment]
Thanks, @DilumAluthge !

And thanks again, @oxinabox -- go ahead and merge and tag!

**Pull request merged**
